version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bukhgalter
      POSTGRES_PASSWORD: devel
      POSTGRES_DB: bukh
    ports:
      - 5432:5432
